### ISSUE TITLE
no tags written

### ISSUE THREAD

**Issue by arpho** [Jack12816/id3-writer#16]
Hi, I am working with nodejs on ubuntu, this is my code:
`
var id3 = require('id3-writer'),file = 'aFile.mp3';
var writer = new id3.Writer();
var File = new id3.File(file),tags = { title: ''afile.mp3,
  artist: 'Walter e Ricky',
  album: 'Fogueo ',
  comment: 'Fase B',
  genre: '50 MI',
  desc: 'just a test'}
writer.setFile(File).write(meta, function(err) {
			console.log('error',err)
        })
`

I get this error
[Error: No available write adapters found]
I read that a suitable adapter is eyed3, I installed it on my  computer, but a do not know howto use it with node, thanks for help

**Comment by Jack12816** [comment]
Hey arpho, how did you installed eyeD3 and which version of Ubuntu/eyeD3 are you using?

The library tries to find the location of eyed3 with the help of system call like this:
``which eyeD3`` which should result in somthing like this: ``/usr/bin/eyeD3``.

If you can verify this then you should double check how you start the nodejs process and if the PATH environment variable includes the path where eyeD3 is located.

**Comment by arpho** [comment]
Hi,
Ubuntu 16.04
Eyed3 0.0.1is  installed via npm -g in /Usr/Local/lib/node_modules/eyed3.
Thanks for your reply
Il mer 4 gen 2017 08:36 Hermann Mayer <notifications@github.com> ha scritto:

Hey arpho, how did you installed eyeD3 and which version of Ubuntu/eyeD3
are you using?

The library tries to find the location of eyed3 with the help of system
call like this:
which eyeD3 which should result in somthing like this: /usr/bin/eyeD3.

If you can verify this then you should double check how you start the
nodejs process and if the PATH environment variable includes the path where
eyeD3 is located.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Jack12816/id3-writer/issues/16#issuecomment-270310760>,
or mute the thread

**Comment by Jack12816** [comment]
You installed another nodejs wrapper via npm. eyeD3 is an utility written in python that you can install  via the package sources of Ubuntu. See: http://packages.ubuntu.com/xenial/python-eyed3

Just install it like this: ``sudo apt-get install python-eyed3``

**Comment by arpho** [comment]
HI,
installed version 0.6.18-1, same error

2017-01-04 9:49 GMT+01:00 Hermann Mayer <notifications@github.com>:

**Comment by Jack12816** [comment]
Could you run this ``which eyeD3`` command and ``eyeD3 -h`` ?

**Comment by arpho** [comment]
wich eyeD3 returns: /usr/local/bin/eyeD3
eyeD3 -h:
Traceback (most recent call last):
  File "/usr/local/bin/eyeD3", line 4, in <module>
    import eyeD3;
  File "/usr/local/lib/python2.7/dist-packages/eyeD3/__init__.py", line 138
    (self.unsync,
SyntaxError: cannot assign to None



2017-01-04 10:29 GMT+01:00 Hermann Mayer <notifications@github.com>:

**Comment by Jack12816** [comment]
I've installed Ubuntu 16.04 and the *eyed3* (python-eyed3 did not bundled the binary) package.
Like this: ``apt-get install eyed3``. Then I was able on this fresh system to execute ``eyeD3 -h`` without errors.

``which eyeD3`` resulted in ``/usr/bin/eyeD3``.  Looks like the utility needs python2. 

I'm a bit confused why the installation path on your system is /usr/**local**/bin/eyeD3.

**Comment by Jack12816** [comment]
@arpho Is this issue now solved?

**Comment by arpho** [comment]
No,i still have the issue

Il sab 7 gen 2017 11:24 Hermann Mayer <notifications@github.com> ha scritto:
